# https://awesome-prometheus-alerts.grep.to/rules
groups:
# node-expporter
- name: Host and Hardware
  rules:
  - alert: 主机可用内存不足
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host out of memory (instance {{ $labels.instance }})
      description: "节点的内存快满了 (< 10% left)\n  VALUE = {{ $value }}"

  - alert: HostMemoryUnderMemoryPressure
    expr: rate(node_vmstat_pgmajfault[1m]) > 1000
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host memory under memory pressure (instance {{ $labels.instance }})
      description: "The node is under heavy memory pressure. High rate of major page faults\n  VALUE = {{ $value }}"

  - alert: 主机流量峰值异常 - 入
    expr: sum by (instance,hostname) (rate(node_network_receive_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: 主机流量峰值异常 (instance {{ $labels.instance }})
      description: "主机网络接口可能接收到太多数据 (> 100 MB/s)\n  VALUE = {{ $value }}"

  - alert: 主机流量峰值异常 - 出
    expr: sum by (instance,hostname) (rate(node_network_transmit_bytes_total[2m])) / 1024 / 1024 > 100
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: 主机流量峰值异常 (instance {{ $labels.instance }})
      description: "主机网络接口可能流出太多数据 (> 100 MB/s)\n  VALUE = {{ $value }}"

  # - alert: 主机磁盘 读 速率异常
  #   expr: sum by (instance,hostname) (rate(node_disk_read_bytes_total[2m])) / 1024 / 1024 > 50
  #   for: 5m
  #   labels:
  #     severity: warning
  #   annotations:
  #     summary: 主机磁盘读速率异常 (instance {{ $labels.instance }})
  #     description: "磁盘可能读取了过多的数据 (> 50 MB/s)\n  VALUE = {{ printf \"%.2f\" $value }}MB/s"

  # - alert: 主机磁盘 写 速率异常
  #   expr: sum by (instance,hostname) (rate(node_disk_written_bytes_total[2m])) / 1024 / 1024 > 50
  #   for: 2m
  #   labels:
  #     severity: warning
  #   annotations:
  #     summary: 主机磁盘写速率异常 (instance {{ $labels.instance }})
  #     description: "磁盘可能写入了过多的数据 (> 50 MB/s)\n  VALUE = {{ printf \"%.2f\" $value }}MB/s"

  # Please add ignored mountpoints in node_exporter parameters like
  # "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
  # Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
  - alert: 主机分区容量使用率
    expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0 and node_filesystem_readonly{fstype!="rootfs"}
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host out of disk space (instance {{ $labels.instance }})
      description: "磁盘 \"{{ $labels.mountpoint }}\" 的容量快满了 (< 10% left)\n  VALUE = {{ printf \"%.2f\" $value }}%"

  # Please add ignored mountpoints in node_exporter parameters like
  # "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)".
  # Same rule using "node_filesystem_free_bytes" will fire when disk fills for non-root users.
  - alert: 主机分区容量耗尽预测，以1小时曲线变化预测接下来24小时可能使用的容量
    expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, mountpoint) predict_linear(node_filesystem_avail_bytes{fstype!~"tmpfs"}[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly == 0 and node_filesystem_readonly{fstype!="rootfs"}
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: 主机磁盘容量将在24小时内耗尽 (instance {{ $labels.instance }})
      description: "按照当前写速率，预计磁盘 \"{{ $labels.mountpoint }}\" 将在未来24小时内耗尽空间\n  VALUE = {{ printf \"%.2f\" $value }}%"

  - alert: 主机 inode 数量使用率
    expr: node_filesystem_files_free / node_filesystem_files * 100 < 10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host out of inodes (instance {{ $labels.instance }})
      description: "磁盘 \"{{ $labels.mountpoint }}\" 的可用索引节点即将耗尽 (< 10% left)\n  VALUE = {{ printf \"%.2f\" $value }}%"

  - alert: 主机 inode 耗尽预测，以1小时曲线变化预测接下来24小时可能使用的 inodes
    expr: node_filesystem_files_free / node_filesystem_files * 100 < 10 and predict_linear(node_filesystem_files_free[1h], 24 * 3600) < 0 and ON (instance, device, mountpoint) node_filesystem_readonly == 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host inodes will fill in 24 hours (instance {{ $labels.instance }})
      description: "Filesystem is predicted to run out of inodes within the next 24 hours at current write rate\n  VALUE = {{ printf \"%.2f\" $value }}%"

  - alert: 主机磁盘 读 延时异常
    expr: (rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1 and rate(node_disk_reads_completed_total[1m]) > 0) * 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Host unusual disk read latency (instance {{ $labels.instance }})
      description: "Disk latency is growing (read operations > 100ms)\n  VALUE = {{ printf \"%.2f\" $value }}ms"

  - alert: 主机磁盘 写 延时异常
    expr: (rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 0.1 and rate(node_disk_writes_completed_total[1m]) > 0) * 1000
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Host unusual disk write latency (instance {{ $labels.instance }})
      description: "Disk latency is growing (write operations > 100ms)\n  VALUE = {{ printf \"%.2f\" $value }}ms"

  - alert: 主机 Cpu 过高
    expr: 100 - (avg by(instance,hostname) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 90
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: 主机 CPU 负载过高 (instance {{ $labels.instance }})
      description: "CPU 负载已经大于 90%\n  VALUE = {{ printf \"%.2f\" $value }}%"

  - alert: HostCpuStealNoisyNeighbor
    expr: avg by(instance,hostname) (rate(node_cpu_seconds_total{mode="steal"}[5m])) * 100 > 10
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host CPU steal noisy neighbor (instance {{ $labels.instance }})
      description: "CPU steal is > 10%. A noisy neighbor is killing VM performances or a spot instance may be out of credit.\n  VALUE = {{ printf \"%.2f\" $value }}%"

  # 3000 context switches is an arbitrary number.
  # Alert threshold depends on nature of application.
  # Please read: https://github.com/samber/awesome-prometheus-alerts/issues/58
  # - alert: 主机上下文切换
  #   expr: (rate(node_context_switches_total[5m])) / (count without(cpu, mode) (node_cpu_seconds_total{mode="idle"})) > 3000
  #   for: 5m
  #   labels:
  #     severity: warning
  #   annotations:
  #     summary: "主机上下文切换 (instance {{ $labels.instance }})"
  #     description: "主机的上下文切换已经大于 3000/s\n  VALUE = {{ printf \"%.1f\" $value }}"

  - alert: 主机交换空间使用警告
    expr: (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: 主机交换空间快用完了 (instance {{ $labels.instance }})
      description: "交换空间使用超过 80%\n  VALUE = {{ printf \"%.2f\" $value }}%"

  - alert: HostSystemdServiceCrashed
    expr: node_systemd_unit_state{state="failed"} == 1
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host systemd service crashed (instance {{ $labels.instance }})
      description: "systemd service crashed\n  VALUE = {{ $value }}"

  # 物理机温度超过 xx 度
  - alert: 主机物理组件温度过高
    expr: node_hwmon_temp_celsius > 75
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: 物理温度过高 (instance {{ $labels.instance }})
      description: "主机物理温度超过 75℃\n  VALUE = {{ printf \"%.2f\" $value }}℃"

  - alert: HostNodeOvertemperatureAlarm
    expr: node_hwmon_temp_crit_alarm_celsius == 1
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Host node overtemperature alarm (instance {{ $labels.instance }})
      description: "Physical node temperature alarm triggered\n  VALUE = {{ $value }}"

  - alert: HostRaidArrayGotInactive
    expr: node_md_state{state="inactive"} > 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Host RAID array got inactive (instance {{ $labels.instance }})
      description: "RAID array {{ $labels.device }} is in degraded state due to one or more disks failures. Number of spare drives is insufficient to fix issue automatically.\n  VALUE = {{ $value }}"

  - alert: HostRaidDiskFailure
    expr: node_md_disks{state="failed"} > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host RAID disk failure (instance {{ $labels.instance }})
      description: "At least one device in RAID array on {{ $labels.instance }} failed. Array {{ $labels.md_device }} needs attention and possibly a disk swap\n  VALUE = {{ $value }}"

  # 运行的节点中发现有不同版本的内核
  # - alert: 主机内核版本有偏差
  #   expr: count(sum(label_replace(node_uname_info, "kernel", "$1", "release", "([0-9]+.[0-9]+.[0-9]+).*")) by (kernel)) > 1
  #   for: 6h
  #   labels:
  #     severity: warning
  #   annotations:
  #     summary: 主机内核版本有不一样的 (instance {{ $labels.instance }})
  #     description: "当前运行的主机内核版本有差别\n  VALUE = {{ $value }}"

  - alert: 检测到主机 OOM Kill
    expr: increase(node_vmstat_oom_kill[1m]) > 0
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: 检测到主机 OOM Kill (instance {{ $labels.instance }})
      description: "检测到 OOM\n  VALUE = {{ $value }}"

  - alert: 检测到主机EDAC可纠正的错误
    expr: increase(node_edac_correctable_errors_total[1m]) > 0
    for: 5m
    labels:
      severity: info
    annotations:
      summary: 主机EDAC可纠正的错误 (instance {{ $labels.instance }})
      description: "在过去5分钟内，EDAC报告了{{ printf \"%.0f\" $value }}个可纠正的内存错误"

  - alert: 检测到主机EDAC不可纠正的错误
    expr: node_edac_uncorrectable_errors_total > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: 主机EDAC不可纠正的错误 (instance {{ $labels.instance }})
      description: "在过去5分钟内，EDAC报告了{{ printf \"%.0f\" $value }}个不可纠正的内存错误[衰]"

  - alert: 主机网络接收错误
    expr: rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: Host Network Receive Errors (instance {{ $labels.instance }})
      description: "主机 {{ $labels.instance }} 接口 {{ $labels.device }} 在最后两分钟出现了 {{ printf \"%.0f\" $value }} 接收错误.\n  VALUE = {{ $value }}"

  - alert: 主机网络传输错误
    expr: rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: 主机网络传输错误 (instance {{ $labels.instance }})
      description: "主机 {{ $labels.instance }} 接口 {{ $labels.device }} 在最后两分钟出现了 {{ printf \"%.0f\" $value }} 传输错误.\n  VALUE = {{ $value }}"

  - alert: 主机网络接近饱和
    expr: (rate(node_network_receive_bytes_total{device!~"^tap.*"}[1m]) + rate(node_network_transmit_bytes_total{device!~"^tap.*"}[1m])) / node_network_speed_bytes{device!~"^tap.*"} > 0.8 < 10000
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: 主机网卡接近饱和 (instance {{ $labels.instance }})
      description: "网卡 \"{{ $labels.device }}\" 在主机 \"{{ $labels.instance }}\" 上正在超负荷传输.\n  VALUE = {{ $value }}"

  - alert: 主机链接状态跟踪
    expr: node_nf_conntrack_entries / node_nf_conntrack_entries_limit > 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Host conntrack limit (instance {{ $labels.instance }})
      description: "跟踪的数量接近极限\n  VALUE = {{ $value }}"

  - alert: 主机时间没有正常同步
    expr: (node_timex_offset_seconds > 0.05 and deriv(node_timex_offset_seconds[5m]) >= 0) or (node_timex_offset_seconds < -0.05 and deriv(node_timex_offset_seconds[5m]) <= 0)
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: 主机时间没有正常同步 (instance {{ $labels.instance }})
      description: "检测到主机时间服务未启动或没有正常工作.\n  VALUE = {{ $value }}"

  # 这个指标需要启动一个时间同步服务(chronyd,ntpd)并且有可以访问的时间服务器(或使用互联网的时间服务器)
  - alert: 主机与时间服务器失联
    # 排除了一个不需要时间同步的主机
    expr: min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16 and node_timex_sync_status{hostname!="192.168.12.223"}
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: 主时间服务器失联，请检查网络状况 (instance {{ $labels.instance }})
      description: "主机时钟未同步.\n  VALUE = {{ $value }}"