version: '3'

services:
  db:
    # image: mariadb:10.7.1-focal
    image: cr.zbxsoft.com/3rd/mariadb:10.7.1-focal
    container_name: matomo_db
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Xd6Vu@r5R9~M
    env_file:
      - ./db.env

  app:
    # image: matomo:4.5.0-fpm-alpine
    # image: cr.zbxsoft.com/3rd/matomo:4.5.0-fpm-alpine
    image: cr.zbxsoft.com/zbx/matomo:4.5.0-fpm-alpine
    container_name: matomo_app
    restart: always
    links:
      - db
    volumes:
#      - ./config:/var/www/html/config:rw
      - ./config.ini.php:/var/www/html/config/config.ini.php:rw
#      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./db.env

  web:
    # image: nginx:1.21.4-alpine
    image: cr.zbxsoft.com/3rd/nginx:1.21.4-alpine
    container_name: matomo_web
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./matomo.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

volumes:
  db:
  matomo:
