global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    environment: prometheus
rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ["alertmanager:9093"]
      labels: 
        hostname: 'alertmanager'
        type: alert
    scheme: http
    timeout: 10s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
      labels: 
        hostname: 'prometheus'
        type: prom
  - job_name: 'pushgateway'
    # https://prometheus.io/docs/Prometheus/latest/configuration/configuration/#scrape_config
    honor_labels: true
    static_configs:
    - targets: ['pushgateway:9091']
      labels:
        hostname: 'pushgateway'
        type: gateway
  # 使用文件发现
  - job_name: 'file_ds'
    file_sd_configs:
    - files:
      - targets.yml
  # # jenkins
  # - job_name: 'jenkins'
  #   metrics_path: '/prometheus'
  #   static_configs:
  #     - targets: ['jenkins:8080']
  #       labels:
  #         hostname: 'jenkins.ops.cn'
  #         type: jenkins
  # # zipkin
  # - job_name: 'zipkin'
  #   metrics_path: '/prometheus'
  #   static_configs:
  #     - targets: ['zipkin:9411']
  #       labels:
  #         hostname: 'zipkin'
  #         type: zipkin
  # # Eureka - jvm
  # - job_name: 'jvm'
  #   eureka_sd_configs:
  #     - server: http://ip:8761/eureka
  #   relabel_configs:
  #     - source_labels: [__meta_eureka_app_instance_metadata_prometheus_path]
  #       action: replace
  #       target_label: __metrics_path__
  #       regex: (.+)
  # # jvm
  # - job_name: 'jvm'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['ip1:port1']
  #     - targets: ['ip2:port2']
  # # etcd
  # - job_name: 'etcd'
  #   scheme: https
  #   tls_config:
  #       insecure_skip_verify: true
  #   static_configs:
  #     - targets: ['etcd1:2379','etcd2:2379','etcd3:2379']
  # blackbox
  - job_name: 'box_http_2xx'
    scrape_interval: 2m
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://www.baidu.com
        - http://www.baidu.com
        labels:
          hostname: 'black'
          type: blackbox
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  # domain-exporter
  - job_name: 'domain-exporter'
    scrape_interval: 2m
    metrics_path: /probe
    static_configs:
      - targets:
        - baidu.com
        - google.com
        labels:
          type: domain
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: domain-exporter:9222
