#!/bin/bash

# HARBOR_SERVER=harbor.zbx.lab
HARBOR_SERVER=${1:-172.30.1.24}
CA_PATH=/etc/docker/certs.d/${HARBOR_SERVER}

caCrt (){
echo """-----BEGIN CERTIFICATE-----
MIIDwjCCAqqgAwIBAgIUCz4kCDDQCIgVe0gKIwBZwIg9Su4wDQYJKoZIhvcNAQEL
BQAwZzELMAkGA1UEBhMCQ04xEDAOBgNVBAgTB0JlaUppbmcxEDAOBgNVBAcTB0Jl
aUppbmcxDDAKBgNVBAoTA3pieDESMBAGA1UECxMJNFBhcmFkaWdtMRIwEAYDVQQD
EwlaYnhIYXJib3IwHhcNMTkwNjI0MDkzMTAwWhcNMjQwNjIyMDkzMTAwWjBnMQsw
CQYDVQQGEwJDTjEQMA4GA1UECBMHQmVpSmluZzEQMA4GA1UEBxMHQmVpSmluZzEM
MAoGA1UEChMDemJ4MRIwEAYDVQQLEwk0UGFyYWRpZ20xEjAQBgNVBAMTCVpieEhh
cmJvcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAO8KwGNM9K3b73ef
196RYxEa6rn1e0HyW/v3SzVOxPJmYr4B6csr9A+LdqdUBiVm5OgWH+mArHS9AHsW
6VKDmy9XxLv8wqF1W8KMwEOjNB2VlR8UpBwA+2rQ87NarlI86pl1d9bIPlN2Ggr6
OS1c0zkeEomyLBMTSAQ65x04AklxPi0Lxo0nDi8+Te6K98riv0XpDhDWjg9xPOX6
1kuSj0nJsPQog4F7qaBG/9mzI3AdJbSu5iu70ucQ8AJ/hOX61AykhuX6frZMNIqu
IDCKFValFpzD1H1aaELNEa8yO663MC2IjxE8eYeud2wy88Nq7cLBnvGrsXoT6t2R
XdyGhhsCAwEAAaNmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
AQIwHQYDVR0OBBYEFGnoLpAsbrv6qchXJ50PuXsV7W+tMB8GA1UdIwQYMBaAFGno
LpAsbrv6qchXJ50PuXsV7W+tMA0GCSqGSIb3DQEBCwUAA4IBAQDB6xyJ+0MOnPPa
lifeELifXYhrqjEnO1xlD8AsrKuYBKAhgR7OtYRn3mYNYmOlBQu66PAkH1cqQmk4
dAhn50ibKdlKx0nD+3H7UriV/E7iSDYQVunxJJ5N4Pf/QB+Dxe5ksMP4UGJFkrUl
HzKQXsKmt2xUCqb+aLE+w83l3I4G6vPfe/IlXu4ojB8xrpEey8AxLzfgBGESaaxx
LI+JGIXdvYvw/tqpSRAB9Sn5NNpTQpCgC83CrTJ20eizbeDGcfXPM4AqZjDmdcCb
U2W1j51TVj7B2U0dRGhfMIYOunDOYcrDLwVQX//0pFsiLIux0ji/e9o21wKh/6i1
UZCsaYOi
-----END CERTIFICATE-----""" > ${CA_PATH}/ca.crt
}

if [[ ${USER} != "root" ]];then echo "Hint: Use 'root' Execute."; exit 1;fi
[[ -d ${CA_PATH} ]] || mkdir -p ${CA_PATH}
if [[ -f ${CA_PATH}/ca.crt ]];then
   echo "[INFO] Path: ${CA_PATH}/ca.crt is Exists."
   caCrt
else
   caCrt
   [[ $? == 1 ]] && echo -e "[ERROR] Path: ${CA_PATH}/ca.crt Add is Failed." || echo "[INFO] Path: ${CA_PATH}/ca.crt Add is Successful."
fi
